### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Anomalyhun** [ful1e5/BreezeX_Cursor#16]
Please make a tutorial How to do the manual build for a human that doesn't know what to do.

**Comment by tony-aln** [comment]
Hi, on the homepage Readme.md https://github.com/ful1e5/BreezeX_Cursor#readme there are links to the files and instructions on how to install them depending on your system. Reply here if you got any further questions.

**Comment by tony-aln** [comment]
To build, you need to install the required packages and follow the instructions for your system. Reply here if you get stuck anywhere.

**Comment by Anomalyhun** [comment]
Do I need to install every package and build dependency?

**Comment by ful1e5** [comment]
I will update the documentation soon. However, since English is not my primary language, it takes time for me to write documents and answer issues.

Thanks for your patience.
