### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by Anomalyhun** [ful1e5/BreezeX_Cursor#17]
PLEASE!!!!!!!!!!!!! Can you build all the sizes of the cursors for windows. I am peace of shit at programming and I am a f*cking beginner. I will be very thankful.

**Comment by ful1e5** [comment]
[BreezeX-Black-Windows.zip](https://github.com/ful1e5/BreezeX_Cursor/files/8511725/BreezeX-Black-Windows.zip)
[BreezeX-Dark-Windows.zip](https://github.com/ful1e5/BreezeX_Cursor/files/8511726/BreezeX-Dark-Windows.zip)
[BreezeX-Light-Windows.zip](https://github.com/ful1e5/BreezeX_Cursor/files/8511727/BreezeX-Light-Windows.zip)

**Comment by Anomalyhun** [comment]
Oh my god! Thank you!!!!!!!<3333333333333
