### ISSUE TITLE
Found a problem using Actions auto build

### ISSUE THREAD

**Issue by T0BUINO** [ful1e5/BreezeX_Cursor#20]
I tried to use the Actions to build a bigger size cursors. But I just got those errors

[9_Generating `BreezeX` Cursor Theme.txt](https://github.com/ful1e5/BreezeX_Cursor/files/9552470/9_Generating.BreezeX.Cursor.Theme.txt)

And then I looked into your Actions builds, I found that your build uses the **clickgen 1.2.0**

So I specified the clickgen version to 1.2.0, then it worked just fine. 

And I would like to know whether the latest clickgen is compatible with this project code anymore.

I'm a rookie in the rookie, so I can only open up a new issue, hope I'm not disturbing you.😵

**Comment by ful1e5** [comment]
Yes, you are right. The code of this project is compatible with clickgen1.2.0. I will update the source code shortly. Thanks for reporting.

**Comment by T0BUINO** [comment]
> Yes, you are right. The code of this project is compatible with clickgen1.2.0. I will update the source code shortly. Thanks for reporting.

you're welcome 😀
