### ISSUE TITLE
from clickgen.util import PNGProvider ModuleNotFoundError: No module named 'clickgen.util'

### ISSUE THREAD

**Issue by kouhe3** [ful1e5/BreezeX_Cursor#21]
File "build.py", line 7, in <module>
    from src.configure import get_config
  File "/workspaces/BreezeX_Cursor/builder/src/configure.py", line 7, in <module>
    from clickgen.util import PNGProvider
ModuleNotFoundError: No module named 'clickgen.util'

![image](https://user-images.githubusercontent.com/25522053/192150865-c8967a29-dbd7-4bf6-8e0c-d18056a2ee79.png)

**Comment by ful1e5** [comment]
You need to install `clickgen 1.2.0` because `clickgen>2.0.0` has been refactored.
you can install clickgen1.2.0 via pip:
```bash
pip install clickgen==1.2.0
```
#### Links
- [clicken 1.2.0 PyPi page](https://pypi.org/project/clickgen/1.2.0)
- [clickgen notices board](https://github.com/ful1e5/clickgen#notices)
