### ISSUE TITLE
Waiting cursor looks a bit weird

### ISSUE THREAD

**Issue by ixti** [ful1e5/BreezeX_Cursor#23]
It might be the design choice, so feel free to close the issue, but IMO rounded square background makes it look a bit off.

---

![image](https://user-images.githubusercontent.com/94782/197839321-1a6d5e39-f7ce-4942-aa69-c571ca08ca15.png)

---

I'd expect it to be more like in Bibata:

---

![image](https://user-images.githubusercontent.com/94782/197839925-4f77c1c5-0fc7-4b2b-a5be-6f9fa4ece7a3.png)

---

**Comment by ful1e5** [comment]
Patched in [v2.0.1](https://github.com/ful1e5/BreezeX_Cursor/releases/tag/v2.0.1)
