### ISSUE TITLE
2 additional select pointers in Windows 11?

### ISSUE THREAD

**Issue by BobbyWibowo** [ful1e5/BreezeX_Cursor#24]
Hey there, it seems we have 2 additional select pointers in Windows 11 (or maybe they were already there long ago, but I never noticed)
![screenshot](https://i.fiery.me/0py8.png)

I was wondering if you'd be up to do custom works for those too

---

On a side note, I hadn't been able to find where exactly those 2 are being used, so it doesn't really bother me at the moment

**Comment by ful1e5** [comment]
@BobbyWibowo I can't see the image you attached. Could you please reattach it?

**Comment by BobbyWibowo** [comment]
@ful1e5
Here you go,
<img width="299" alt="ShareX_rundll32_20240629-200600" src="https://github.com/ful1e5/BreezeX_Cursor/assets/9364930/52fce524-98d8-4a94-a1a6-3ce637e5bb90">

**Comment by ful1e5** [comment]
@BobbyWibowo I'll patch that soon.

**Comment by ful1e5** [comment]
Fixed in [v2.0.1](https://github.com/ful1e5/BreezeX_Cursor/releases/tag/v2.0.1)
